### ISSUE TITLE
I have the same problem

### ISSUE THREAD

**Issue by barakplasma** [danbruder/parcel-rust-strings#1]
Hi there,

I too have the same problem with Parcel when returning a string from Rust.

Did you figure out how to fix it?

**Comment by barakplasma** [comment]
Also mentioned in this blog post towards the end: https://justinjordan.io/blog/getting-started-with-wasm-using-parceljs-and-rust/

**Comment by barakplasma** [comment]
Here's the closest I could find to a solution: https://rustwasm.github.io/docs/wasm-bindgen/reference/types/string.html

**Comment by danbruder** [comment]
I never got to the bottom of it unfortunately.
